const express = require('express')
const lessonsController = require('../controllers/lessonsController')
const router = express.Router()
router.get('/', lessonsController.list)
router.get('/:id', lessonsController.detail)
router.get('/:id/status', lessonsController.status)
router.post('/view', lessonsController.view)
router.post('/quiz/submit', lessonsController.submitQuiz)
router.post('/task/submit', lessonsController.submitTask)
router.get('/:id/attempts', lessonsController.attempts)
router.get('/:id/submissions', lessonsController.submissions)
router.post('/task/mark', lessonsController.markTask)
router.post('/quiz/mark', lessonsController.markQuiz)
module.exports = router
